// <auto-generated />
using System;
using Caraspirator.Library.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caraspirator.Library.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240216213640_firstmigrate")]
    partial class firstmigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Caraspirator.Library.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("category_image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("parent_id")
                        .HasColumnType("int");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("category_id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            category_id = 1,
                            Category_Name = "T-Shirt",
                            category_image = "http://admin.queensudan.com//images//queenimage/categoryicon/Tshirtrealicon.png",
                            created_at = new DateTime(2024, 2, 16, 21, 36, 40, 491, DateTimeKind.Local).AddTicks(3032),
                            is_active = true,
                            parent_id = 0,
                            slug = "T-Shirt",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            category_id = 2,
                            Category_Name = "Dresses",
                            category_image = "http://admin.queensudan.com//images//queenimage/categoryicon/Dreesrealicon.png",
                            created_at = new DateTime(2024, 2, 16, 21, 36, 40, 491, DateTimeKind.Local).AddTicks(3084),
                            is_active = true,
                            parent_id = 0,
                            slug = "Dresses",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            category_id = 3,
                            Category_Name = "Blouses",
                            category_image = "http://admin.queensudan.com//images//queenimage/categoryicon/blouserealicon.png",
                            created_at = new DateTime(2024, 2, 16, 21, 36, 40, 491, DateTimeKind.Local).AddTicks(3088),
                            is_active = true,
                            parent_id = 0,
                            slug = "Blouses",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            category_id = 4,
                            Category_Name = "Bottoms",
                            category_image = "http://admin.queensudan.com//images//queenimage/categoryicon/blouserealicon.png",
                            created_at = new DateTime(2024, 2, 16, 21, 36, 40, 491, DateTimeKind.Local).AddTicks(3092),
                            is_active = true,
                            parent_id = 0,
                            slug = "Bottoms",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            category_id = 5,
                            Category_Name = "Beauty",
                            category_image = "http://admin.queensudan.com//images//queenimage/categoryicon/Beauty.png",
                            created_at = new DateTime(2024, 2, 16, 21, 36, 40, 491, DateTimeKind.Local).AddTicks(3096),
                            is_active = true,
                            parent_id = 0,
                            slug = "Beauty",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            category_id = 6,
                            Category_Name = "Bag",
                            category_image = "http://admin.queensudan.com//images//queenimage/categoryicon/bagrealicon.png",
                            created_at = new DateTime(2024, 2, 16, 21, 36, 40, 491, DateTimeKind.Local).AddTicks(3100),
                            is_active = true,
                            parent_id = 0,
                            slug = "Bag",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            category_id = 7,
                            Category_Name = "Jewellery",
                            category_image = "http://admin.queensudan.com//images//queenimage/categoryicon/jewelleryrealicon.png",
                            created_at = new DateTime(2024, 2, 16, 21, 36, 40, 491, DateTimeKind.Local).AddTicks(3103),
                            is_active = true,
                            parent_id = 0,
                            slug = "Jewellery",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            category_id = 8,
                            Category_Name = "Shoes",
                            category_image = "http://admin.queensudan.com//images//queenimage/categoryicon/shoesrealicon.png",
                            created_at = new DateTime(2024, 2, 16, 21, 36, 40, 491, DateTimeKind.Local).AddTicks(3107),
                            is_active = true,
                            parent_id = 0,
                            slug = "Shoes",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            category_id = 9,
                            Category_Name = "scarfs",
                            category_image = "http://admin.queensudan.com//images//queenimage/categoryicon/categoryscrfus.png",
                            created_at = new DateTime(2024, 2, 16, 21, 36, 40, 491, DateTimeKind.Local).AddTicks(3111),
                            is_active = true,
                            parent_id = 0,
                            slug = "scarfs",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            category_id = 10,
                            Category_Name = "Soft Clothes",
                            category_image = "http://admin.queensudan.com//images//queenimage/categoryicon/SoftCategory.png",
                            created_at = new DateTime(2024, 2, 16, 21, 36, 40, 491, DateTimeKind.Local).AddTicks(3115),
                            is_active = true,
                            parent_id = 0,
                            slug = "Soft Clothes",
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Caraspirator.Library.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastLogin_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("EspUser");
                });
#pragma warning restore 612, 618
        }
    }
}
